 # Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config
- name: buybc-permit.buybc.gov.bc.ca
  version: 1.0.0
  description: The buybc-permit credential issued by buybc.gov.bc.ca
  attributes:
    entity_name:
      description_en: The legal name of entity
      label_en: Name
      data_type: ui_name
      required: true
    corp_num:
      description_en: Registration/Incorporation Number or Identifying Number
      label_en: Registration ID
      data_type: ui_text
      required: true
    license_number:
      description_en: License Identifying Number
      label_en: License Number
      data_type: ui_text
      required: true
    license_type:
      description_en: Type of the license (Marketing / Certification)
      label_en: License Type
      data_type: ui_select
      required: true
    status:
      description_en: Status of the credential
      label_en: Credential Status
      data_type: ui_select
      required: true
    status_reason:
      description_en: Reason for status of the credential
      label_en: Credential Status Reason
      data_type: ui_select
      required: true
    license_effective_date:
      description_en: Date license is effective
      label_en: License Effective Date
      data_type: ui_date
      required: true
    issue_date:
      description_en: Date credential is issued
      label_en: Credential Issued Date
      data_type: ui_date
      required: true
    effective_date:
      description_en: Date credential is effective
      label_en: Credential Effective Date
      data_type: ui_date
      required: true
    expiry_date:
      description_en: Date credential expires
      label_en: Credential Expiry Date
      data_type: ui_date
      required: true
### eof ###

