# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

issuers:
  myorg:
    name: BuyBC
    abbreviation: buybc.gov.bc.ca
    url: https://www.buybc.gov.bc.ca.ca/buybc.gov.bc.ca-info-page
    email: info@buybc.gov.bc.ca
    logo_path: ../assets/img/buybc.gov.bc.ca-logo.jpg
    endpoint: $ENDPOINT_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    credential_types:
      - description: The buybc-permit credential issued by buybc.gov.bc.ca
        schema: buybc-permit.buybc.gov.bc.ca
        issuer_url: $ENDPOINT_URL/buybc.gov.bc.ca/buybc-permit
        depends_on:
          - greenlight_registration
        credential:
          effective_date:
            input: effective_date
            from: claim
        topic:
          source_id:
            input: corp_num
            from: claim
          type:
            input: my-registration.buybc.gov.bc.ca
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: legal_name
                from: claim
              type:
                input: entity_name
                from: value
          - model: attribute
            fields:
              type:
                input: corp_num
                from: value
              value:
                input: corp_num
                from: claim
          - model: attribute
            fields:
              type:
                input: license_number
                from: value
              value:
                input: license_number
                from: claim
          - model: attribute
            fields:
              type:
                input: license_type
                from: value
              value:
                input: license_type
                from: claim
          - model: attribute
            fields:
              type:
                input: status
                from: value
              value:
                input: status
                from: claim
          - model: attribute
            fields:
              type:
                input: corp_num
                from: value
              value:
                input: corp_num
                from: claim
          - model: attribute
            fields:
              type:
                input: status_reason
                from: value
              value:
                input: status_reason
                from: claim
          - model: attribute
            fields:
              type:
                input: license_effective_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: license_effective_date
                from: claim
          - model: attribute
            fields:
              type:
                input: issue_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: issue_date
                from: claim
          - model: attribute
            fields:
              type:
                input: effective_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: effective_date
                from: claim
          - model: attribute
            fields:
              type:
                input: expiry_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: expiry_date
                from: claim
verifiers:
  bctob:
    name: BC OrgBook
    alias: vcr-agent
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      agent_admin_url: $TOB_AGENT_ADMIN_URL

proof_requests:
  greenlight_registration:
    version: "1.0.0"
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: Registered Corporation
          version: "1.0.3"
        attributes:
          - corp_num
          - legal_name
### eof ###
